model_path: models/phi-3-mini-4k-instruct.Q4_K_M.gguf
temperature: 0.6
max_tokens: 8192
context_window: 8192
output_dir: tests
metadata_file: metadata.json
repo_path: .
max_fix_attempts: 0
coverage_threshold: 50
log_level: INFO
